# Generated by Django 5.0.5 on 2024-09-24 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='amount_due',
        ),
    ]
