# Generated by Django 5.0.5 on 2024-09-24 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_remove_fee_amount_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='final_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='scholarship_reduction',
        ),
    ]
