# Generated by Django 5.0.5 on 2024-09-24 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0003_rename_final_amount_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
