# Generated by Django 5.0.5 on 2024-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_exam_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='assignment_marks',
            field=models.FloatField(default=0),
        ),
    ]
