# Generated by Django 5.0.5 on 2024-08-31 06:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_leave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=10)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback_reply', models.TextField(blank=True, null=True)),
                ('reply_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(limit_choices_to={'role__in': ['student', 'staff']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
