# Generated by Django 5.0.5 on 2024-09-14 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_name',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
