# Generated by Django 5.1.1 on 2024-10-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_remove_feedback_feedback_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
