# Generated by Django 5.1.1 on 2024-10-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_schooluser_password_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='password_reset_token',
        ),
    ]
