# Generated by Django 5.1.1 on 2024-10-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_remove_schooluser_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
